### ISSUE TITLE
All commands fail when  slash character is present at the end of host name

### ISSUE THREAD

**Issue by ciur** [papermerge/papermerge-cli#15]
For example:

    $ export PAPERMERGE_CLI__HOST=http://papermerge.local/
    $ export PAPERMERGE_CLI__TOKEN=e4e9206c6f2b2.. balh ..a0b9eefd28dba

Notice the slash ``/`` at the end of host name. Now if I invoke list command for example:

     $ papermerge-cli list

The result is:
  
    Traceback (most recent call last):
      File "/home/eugen/.local/bin/papermerge-cli", line 8, in <module>
        sys.exit(cli())
      File "/home/eugen/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
        return self.main(*args, **kwargs)
      File "/home/eugen/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
        rv = self.invoke(ctx)
      File "/home/eugen/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/eugen/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/eugen/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
        return __callback(*args, **kwargs)
      File "/home/eugen/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/home/eugen/.local/lib/python3.10/site-packages/papermerge_cli/main.py", line 100, in _list
        perform_list(
      File "/home/eugen/.local/lib/python3.10/site-packages/papermerge_cli/rest.py", line 135, in perform_list
        response = api_instance.users_me_retrieve()
      File "/home/eugen/.local/lib/python3.10/site-packages/papermerge_restapi_client/paths/api_users_me_/get.py", line 124, in users_me_retrieve
        return self._users_me_retrieve_oapg(
      File "/home/eugen/.local/lib/python3.10/site-packages/papermerge_restapi_client/paths/api_users_me_/get.py", line 101, in _users_me_retrieve_oapg
        api_response = response_for_status.deserialize(response, self.api_client.configuration)
      File "/home/eugen/.local/lib/python3.10/site-packages/papermerge_restapi_client/api_client.py", line 922, in deserialize
        raise ApiValueError(
    papermerge_restapi_client.exceptions.ApiValueError: Invalid content_type returned. Content_type='text/html' was returned when only {'application/vnd.api+json'} are defined for status_code=200

It is expected that commands (e.g. list) will work when slash character is present at the end of the host name.

**Comment by ciur** [comment]
https://github.com/papermerge/papermerge-cli/pull/16
